# Site settings
title: Ronan McHugh
email: dontemailme@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my sample website built using jekyll.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ronan-mch.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  ronan-mch

# Build settings
highlighter: rouge
markdown: kramdown
